owner: calkit
name: example-basic
title: Basic Calkit example
description: A basic Calkit example project.
git_repo_url: https://github.com/calkit/example-basic
dependencies:
  - docker
  - conda
questions:
  - Can we make reproducibility simple?
environments:
  py:
    path: environment.yml
    kind: conda
    description: A Python environment
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeX Live via Docker.
pipeline:
  stages:
    collect-data:
      kind: python-script
      script_path: scripts/collect-data.py
      environment: py
      outputs:
        - data/raw/data.csv
    plot-voltage:
      kind: python-script
      script_path: scripts/plot-voltage.py
      environment: py
      inputs:
        - from_stage_outputs: collect-data
      outputs:
        - figures/voltage-time-series.png
    build-paper:
      kind: latex
      target_path: paper/paper.tex
      environment: tex
      inputs:
        - figures
      outputs:
        - paper/paper.pdf
datasets:
  - path: data/raw/data.csv
    title: Raw data
    description: This is raw voltage data.
    stage: collect-data
figures:
  - path: figures/voltage-time-series.png
    title: Raw voltage time series
    description: A plot of the raw voltage time series.
    stage: plot-voltage
publications:
  - path: paper/paper.pdf
    title: The paper
    description: This is the paper.
    stage: build-paper
