stages:
  collect-data:
    cmd: calkit runenv -n py -- python scripts/collect-data.py
    deps:
      - scripts/collect-data.py
      - environment.yml
    outs:
      - data/raw/data.csv
  plot-voltage:
    cmd: calkit runenv -n py -- python scripts/plot-voltage.py
    deps:
      - scripts/plot-voltage.py
      - data/raw/data.csv
      - environment.yml
    outs:
      - figures/voltage-time-series.png
  build-paper:
    cmd: >
      calkit runenv -n tex --
      "cd paper && latexmk -interaction=nonstopmode -pdf paper.tex"
    deps:
      - figures
      - paper/paper.tex
    outs:
      - paper/paper.pdf
