stages:
  _check-env-py:
    cmd: calkit check conda-env --file environment.yml --output 
      .calkit/env-locks/py.yml
    deps:
      - environment.yml
    outs:
      - .calkit/env-locks/py.yml:
          cache: false
          persist: true
    always_changed: true
  _check-env-tex:
    cmd: calkit check docker-env texlive/texlive:latest-full -o 
      .calkit/env-locks/tex.json
    deps: []
    outs:
      - .calkit/env-locks/tex.json:
          cache: false
          persist: true
    always_changed: true
  collect-data:
    cmd: calkit xenv -n py --no-check -- python 
      scripts/collect-data.py
    deps:
      - scripts/collect-data.py
      - .calkit/env-locks/py.yml
    outs:
      - data/raw/data.csv
  plot-voltage:
    cmd: calkit xenv -n py --no-check -- python 
      scripts/plot-voltage.py
    deps:
      - scripts/plot-voltage.py
      - .calkit/env-locks/py.yml
      - data/raw/data.csv
    outs:
      - figures/voltage-time-series.png
  build-paper:
    cmd: calkit xenv -n tex --no-check -- latexmk -cd 
      -interaction=nonstopmode -pdf paper/paper.tex
    deps:
      - paper/paper.tex
      - figures
      - .calkit/env-locks/tex.json
    outs:
      - paper/paper.pdf
