name: Run pipeline

on: push

permissions:
  contents: write

jobs:
  main:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          auto-activate-base: true
          conda-remove-defaults: true
      - run: pip install calkit-python
      - name: Restore DVC cache
        id: cache-dvc-restore
        uses: actions/cache/restore@v4
        with:
          path: .dvc/cache
          key: ${{ runner.os }}-dvc-cache
      - run: calkit config remote-auth
        env:
          CALKIT_DVC_TOKEN: ${{ secrets.CALKIT_DVC_TOKEN }}
      - run: dvc pull
      - run: calkit run
      - run: calkit save -am "Run pipeline"
        env:
          CALKIT_DVC_TOKEN: ${{ secrets.CALKIT_DVC_TOKEN }}
      - name: Save DVC cache
        id: cache-dvc-save
        uses: actions/cache/save@v4
        with:
          path: .dvc/cache
          key: ${{ steps.cache-dvc-restore.outputs.cache-primary-key }}
